apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-0www
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-0www
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-0www
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-0www
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-0www
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nvrg-tenant/status-quarkus-io/statusquarkusio-0www@sha256:ccf4714c967994abc00d78976a62d7a015cb21f6d8363d387ca67f2e92804be5
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
